version: "3.9"

services:

  oracle:
    image: loliconneko/oracle-ee-11g
    container_name: oracle-db
    environment:
      ORACLE_ALLOW_REMOTE: "yes"
      ORACLE_DISABLE_ASYNCH_IO: "true"
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - socobis-net

  socobis-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socobis-wildfly
    depends_on:
      - oracle
    ports:
      - "8080:8080"
    networks:
      - socobis-net

networks:
  socobis-net:

volumes:
  oracle-data:
